name: Command
version: ${project.version}
main: me.command.command.Main
api-version: 1.16
authors: [ Jozo_85 ]
description: command
website: kaktusekplay.tk
commands:
  clear:
    description: Clear inventory
    usage: /<command>
